@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-6xl space-y-6">
    <div role="status" class="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 shadow-sm">
        <div><p class="font-semibold text-amber-950">Previewing as {{ $previewStudent?->name ?? 'a generic learner' }}</p><p class="mt-1 text-xs text-amber-900">Read-only learner preview · Signed in as {{ auth('web')->user()->name }}</p></div>
        <form method="POST" action="{{ route('admin.lms.preview.exit',$preview['id']) }}">@csrf<x-lms.button tone="neutral">Exit preview</x-lms.button></form>
    </div>
    <header><h1 dir="auto" class="font-serif text-3xl font-bold">{{ $course->title }}</h1><p class="mt-2 text-sm text-slate-600">Explore learning content and current availability. Progress, submissions and playback allowances stay unchanged.</p>@if($progress)<p class="mt-3 text-sm font-semibold text-amber-800">{{ $progress['status'] }} · {{ $progress['percent'] }}% complete</p>@endif</header>
    <div class="grid gap-6 lg:grid-cols-[18rem_minmax(0,1fr)]">
        <nav aria-label="Preview curriculum" class="space-y-2 rounded-2xl border border-slate-200 bg-white p-4">
            <a href="{{ route('admin.lms.preview.show',$preview['id']) }}" class="flex min-h-11 items-center rounded-xl px-3 text-sm font-semibold text-amber-800">Course overview</a>
            @forelse($lessons as $item)<a dir="auto" href="{{ route('admin.lms.preview.lesson',[$preview['id'],$item->id]) }}" @if($lesson?->id===$item->id) aria-current="page" @endif class="block min-h-11 break-words rounded-xl border border-slate-100 px-3 py-3 text-sm font-semibold hover:bg-amber-50">{{ $item->title }}@if($progress)<span class="mt-1 block text-xs font-normal text-slate-500">{{ $progress['lessons']->get($item->id)['status'] }}@if(!$progress['lessons']->get($item->id)['allowed']) · Locked @endif</span>@endif</a>@empty<p class="text-sm text-slate-500">No lessons available in this preview.</p>@endforelse
        </nav>
        <section class="min-w-0 space-y-5">
            @if(!$allowed)<div class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 class="text-lg font-semibold">Learning unavailable</h2><p class="mt-3 text-sm text-amber-900">{{ $reason }}</p></div>
            @elseif(!$lesson)<div class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-semibold">Choose a lesson</h2><p class="mt-3 text-sm text-slate-600">{{ $previewStudent ? 'This preview follows the Student’s current access, prerequisites and scheduled unlocks.' : 'Generic preview shows published learning. Select a specific Student to check their access and scheduled unlocks.' }}</p></div>
            @else<h2 dir="auto" class="text-2xl font-semibold">{{ $lesson->title }}</h2>
                @forelse($blocks as $block)<article class="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6">
                    @switch($block['kind'])
                    @case('rich_text')<div dir="auto" class="prose prose-slate max-w-none break-words">{!! $block['payload']['html'] !!}</div>@break
                    @case('image')<img src="{{ $block['url'] }}" alt="{{ $block['payload']['alt'] }}" class="max-h-[36rem] w-full rounded-xl object-contain">@break
                    @case('file')@case('resource')<a href="{{ $block['url'] }}" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-800 underline">{{ $block['payload']['label'] ?? 'Open learning Resource' }}</a>@break
                    @case('external_link')@case('youtube_video')@case('external_video')<p class="text-sm text-slate-600">External learning link</p><a href="{{ $block['payload']['url']??$block['payload']['src']??'#' }}" target="_blank" rel="noopener noreferrer" class="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-amber-800 underline">Open provider in a new tab</a>@break
                    @case('video')<div data-protected-player data-authorize-url="{{ $block['authorizationUrl'] }}" class="space-y-3"><h3 dir="auto" class="font-semibold">{{ $block['label'] }}</h3><div data-video-container class="relative overflow-hidden rounded-xl bg-stone-950"><video playsinline preload="none" disablepictureinpicture disableremoteplayback controlslist="nodownload noremoteplayback nofullscreen" class="aspect-video w-full"></video><span data-video-watermark hidden aria-hidden="true" class="pointer-events-none absolute z-10 rounded bg-black/30 px-2 py-1 text-xs font-semibold text-white/80"></span><div class="flex flex-wrap items-center gap-3 bg-stone-900 p-3 text-sm text-white"><button data-video-play type="button" class="min-h-11 rounded-lg bg-white/15 px-4 font-semibold">Play video</button><label class="flex min-w-0 flex-1 items-center gap-2"><span class="sr-only">Video position</span><input data-video-seek type="range" min="0" max="0" value="0" step="1" aria-label="Video position" class="min-h-11 min-w-0 flex-1" disabled></label><span data-video-time class="text-xs tabular-nums">0:00</span><button data-video-mute type="button" class="min-h-11 px-3">Mute</button><button data-video-fullscreen type="button" class="min-h-11 px-3">Fullscreen</button><button data-video-close type="button" class="min-h-11 px-3">Close player</button></div></div><p data-protected-status role="status" class="text-sm text-slate-600">Select Play video to start secure staff preview.</p><p class="text-xs text-slate-500">Preview playback saves no watched progress.</p></div>@break
                    @case('quiz')<h3 dir="auto" class="text-lg font-semibold">{{ $block['quiz']['title'] }}</h3><p class="mt-2 text-sm text-slate-500">Quiz preview · Answers are disabled.</p><fieldset disabled class="mt-4 space-y-4"><legend class="sr-only">Read-only quiz questions</legend>@foreach($block['quiz']['questions'] as $question)<div class="space-y-2"><p dir="auto" class="break-words text-sm font-semibold">{{ $loop->iteration }}. {{ $question['prompt'] }}</p>@if(in_array($question['type'],['choice','multiple','boolean'],true))@foreach($question['type']==='boolean'?['True','False']:$question['options'] as $option)<label dir="auto" class="flex min-h-11 items-center gap-2 text-sm"><input type="{{ $question['type']==='multiple'?'checkbox':'radio' }}" name="preview-q-{{ $block['id'] }}-{{ $loop->parent->index }}">{{ $option }}</label>@endforeach @else<label class="block text-sm"><span class="sr-only">Response for question {{ $loop->iteration }}</span><textarea rows="2" class="w-full rounded-lg border border-slate-200 bg-slate-50 p-3"></textarea></label>@endif</div>@endforeach</fieldset>@break
                    @case('assignment')<h3 dir="auto" class="text-lg font-semibold">{{ $block['definition']['title'] }}</h3><p dir="auto" class="mt-3 whitespace-pre-wrap break-words text-sm text-slate-700">{{ $block['definition']['instructions'] }}</p><p class="mt-3 text-xs text-slate-500">Accepted response types: {{ implode(', ',$block['definition']['types']) }}. Submissions are disabled in preview.</p>@break
                    @default<p class="text-sm text-slate-500">This learning content is currently unavailable.</p>
                    @endswitch
                </article>@empty<p class="rounded-2xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No ready content in this lesson.</p>@endforelse
            @endif
        </section>
    </div>
</div>
@endsection