@props(['task' => null, 'assignees', 'studentId' => null])
<div class="grid gap-3 sm:grid-cols-2">
    <label class="text-sm font-semibold sm:col-span-2">Task title<input name="title" required maxlength="160" value="{{ old('title', $task?->title) }}" class="mt-1 block w-full rounded-lg border border-slate-300 p-3"></label>
    <label class="text-sm font-semibold">Assigned to<select name="assignee_id" required class="mt-1 block w-full rounded-lg border border-slate-300 p-3">@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((int) old('assignee_id', $task?->assignee_id ?? auth('web')->id()) === (int) $assignee->id)>{{ $assignee->name }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold">Due date (business timezone)<input type="date" name="due_date" value="{{ old('due_date', $task?->due_date?->toDateString()) }}" class="mt-1 block w-full rounded-lg border border-slate-300 p-3"></label>
    <label class="text-sm font-semibold">Student ID (optional)<input type="number" min="1" name="student_id" value="{{ old('student_id', $task?->student_id ?? $studentId) }}" class="mt-1 block w-full rounded-lg border border-slate-300 p-3"></label>
    <label class="text-sm font-semibold">Priority<select name="priority" class="mt-1 block w-full rounded-lg border border-slate-300 p-3">@foreach(['low', 'normal', 'high'] as $priority)<option value="{{ $priority }}" @selected(old('priority', $task?->priority ?? 'normal') === $priority)>{{ ucfirst($priority) }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold">Task status<select name="status" class="mt-1 block w-full rounded-lg border border-slate-300 p-3">@foreach(['open', 'in_progress', 'completed', 'cancelled'] as $status)<option value="{{ $status }}" @selected(old('status', $task?->status ?? 'open') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold sm:col-span-2">Description<textarea name="description" rows="3" maxlength="10000" class="mt-1 block w-full rounded-lg border border-slate-300 p-3">{{ old('description', $task?->description) }}</textarea></label>
</div>
