@props(['student', 'kind', 'record' => null, 'bookings', 'bookingId' => null, 'resources', 'materials', 'plans'])
<form method="POST" action="{{ route('admin.students.teaching.store', [$student, $kind]) }}" class="mt-4 grid gap-4 sm:grid-cols-2">
    @csrf
    @if($record)<input type="hidden" name="record_id" value="{{ $record->id }}">@endif
    @if(!in_array($kind, ['plan', 'milestone'], true))
        <label class="block text-sm font-semibold text-slate-700">Lesson context (optional)<select name="booking_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Student-wide</option>@foreach($bookings as $lesson)<option value="{{ $lesson->id }}" @selected((int)old('booking_id', $record?->booking_id ?? $bookingId) === $lesson->id)>#{{ $lesson->id }} · {{ $lesson->start_at_utc->format('M j, Y') }} · {{ $lesson->sessionType?->title }}</option>@endforeach</select></label>
    @endif
    @switch($kind)
    @case('homework')
        <label class="block text-sm font-semibold text-slate-700">Title<input name="title" type="text" required maxlength="200" value="{{ old('title', $record?->title) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Instructions<textarea name="instructions" required maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('instructions', $record?->instructions) }}</textarea></label></div>
        <label class="block text-sm font-semibold text-slate-700">Assigned date<input name="assigned_date" type="date" required  value="{{ old('assigned_date', $record?->assigned_date?->toDateString() ?? now()->toDateString()) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Due date (optional)<input name="due_date" type="date"   value="{{ old('due_date', $record?->due_date?->toDateString()) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Homework status<select name="status" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="assigned" @selected(old('status', $record?->status) === 'assigned')>assigned</option><option value="in_progress" @selected(old('status', $record?->status) === 'in_progress')>in progress</option><option value="submitted" @selected(old('status', $record?->status) === 'submitted')>submitted</option><option value="completed" @selected(old('status', $record?->status) === 'completed')>completed</option></select></label>
        <label class="block text-sm font-semibold text-slate-700">Practice HTTPS link (optional)<input name="url" type="url"   value="{{ old('url', $record?->url) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Published resource<select name="resource_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Choose a resource</option>@foreach($resources as $resource)<option value="{{ $resource->id }}" @selected((int)old('resource_id', $record?->resource_id) === $resource->id)>{{ $resource->title }}</option>@endforeach</select></label>
        <label class="block text-sm font-semibold text-slate-700">Lesson material (optional)<select name="lesson_material_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">No material reference</option>@foreach($materials as $material)<option value="{{ $material->id }}" @selected((int)old('lesson_material_id', $record?->lesson_material_id) === $material->id)>Lesson #{{ $material->booking_id }} · {{ $material->title }}</option>@endforeach</select></label>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Feedback shared with the student<textarea name="feedback"  maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('feedback', $record?->feedback) }}</textarea></label></div>
        @if($record?->student_response)<p class="whitespace-pre-line break-words rounded-xl bg-slate-50 p-4 text-sm sm:col-span-2"><strong>Student response:</strong> {{ $record->student_response }}</p>@endif
    @break
    @case('plan')
        <label class="block text-sm font-semibold text-slate-700">Plan title<input name="title" type="text" required maxlength="200" value="{{ old('title', $record?->title) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Current level (optional)<input name="current_level" type="text"  maxlength="100" value="{{ old('current_level', $record?->current_level) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Goals<textarea name="goals" required maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('goals', $record?->goals) }}</textarea></label></div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Focus areas<textarea name="focus_areas"  maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('focus_areas', $record?->focus_areas) }}</textarea></label></div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Notes shared with the student<textarea name="notes"  maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('notes', $record?->notes) }}</textarea></label></div>
        <label class="block text-sm font-semibold text-slate-700">Start date<input name="start_date" type="date" required  value="{{ old('start_date', $record?->start_date?->toDateString() ?? now()->toDateString()) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Plan status<select name="status" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="active" @selected(old('status', $record?->status) === 'active')>active</option><option value="paused" @selected(old('status', $record?->status) === 'paused')>paused</option><option value="completed" @selected(old('status', $record?->status) === 'completed')>completed</option></select></label>
    @break
    @case('milestone')
        <label class="block text-sm font-semibold text-slate-700">Learning plan<select name="learning_plan_id" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2">@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected((int)old('learning_plan_id', $record?->learning_plan_id) === $plan->id)>{{ $plan->title }}</option>@endforeach</select></label>
        <label class="block text-sm font-semibold text-slate-700">Milestone title<input name="title" type="text" required maxlength="200" value="{{ old('title', $record?->title) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <label class="block text-sm font-semibold text-slate-700">Milestone status<select name="status" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="pending" @selected(old('status', $record?->status) === 'pending')>pending</option><option value="in_progress" @selected(old('status', $record?->status) === 'in_progress')>in progress</option><option value="completed" @selected(old('status', $record?->status) === 'completed')>completed</option></select></label>
    @break
    @case('preparation')
        <p class="self-end rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Staff only. These notes never appear in the student portal.</p>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Tutor preparation<textarea name="body" required maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('body', $record?->body) }}</textarea></label></div>
    @break
    @case('resource')
        <label class="block text-sm font-semibold text-slate-700">Published resource<select name="resource_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Choose a resource</option>@foreach($resources as $resource)<option value="{{ $resource->id }}" @selected((int)old('resource_id', $record?->resource_id) === $resource->id)>{{ $resource->title }}</option>@endforeach</select></label>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Instructions for this assignment<textarea name="instructions"  maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('instructions', $record?->instructions) }}</textarea></label></div>
    @break
    @case('error')
        <label class="block text-sm font-semibold text-slate-700">Practice category<select name="category" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="pronunciation" @selected(old('category', $record?->category) === 'pronunciation')>pronunciation</option><option value="vocabulary" @selected(old('category', $record?->category) === 'vocabulary')>vocabulary</option><option value="grammar" @selected(old('category', $record?->category) === 'grammar')>grammar</option></select></label>
        <label class="block text-sm font-semibold text-slate-700">Mistake or recurring pattern<input name="mistake" type="text" required maxlength="500" value="{{ old('mistake', $record?->mistake) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Correction<textarea name="correction" required maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('correction', $record?->correction) }}</textarea></label></div>
        <div class="sm:col-span-2"><label class="block text-sm font-semibold text-slate-700">Practice notes<textarea name="notes"  maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('notes', $record?->notes) }}</textarea></label></div>
        <label class="block text-sm font-semibold text-slate-700">Practice status<select name="status" required class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="practising" @selected(old('status', $record?->status) === 'practising')>practising</option><option value="improved" @selected(old('status', $record?->status) === 'improved')>improved</option><option value="resolved" @selected(old('status', $record?->status) === 'resolved')>resolved</option></select></label>
    @break
    @case('tag')
        <label class="block text-sm font-semibold text-slate-700">Teaching tag<input name="label" type="text" required maxlength="40" value="{{ old('label', $record?->label) }}" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2"></label>
        <p class="self-end text-sm text-slate-500">For example: pronunciation, grammar, revision, homework, exam prep.</p>
    @break
    @endswitch
    @if(!in_array($kind, ['preparation', 'milestone'], true))
        <label class="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="hidden" name="student_visible" value="0"><input type="checkbox" name="student_visible" value="1" @checked(old('student_visible', $record?->student_visible ?? false)) class="rounded border-slate-300 text-amber-600">Share with student</label>
    @endif
    <div class="sm:col-span-2"><button class="min-h-11 rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">{{ $record ? 'Save changes' : 'Add '.str_replace('_', ' ', $kind) }}</button></div>
</form>