@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-6xl space-y-6"><x-student-quick-actions :student="$student" /><div><a class="text-sm font-semibold text-amber-800" href="{{ route('admin.students.show', $student) }}">← Student record</a><h1 class="mt-3 font-serif text-3xl font-bold">{{ $student->name }} · Scheduling & holidays</h1></div>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="mb-4 text-xl font-bold">New recurring plan</h2><form method="POST" action="{{ route('admin.recurring.store', $student) }}" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@csrf<input type="hidden" name="idempotency_key" value="{{ \Illuminate\Support\Str::uuid() }}">
<label class="text-sm font-semibold">Lesson type<select name="session_type_id" required class="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3">@foreach($sessionTypes as $type)<option value="{{ $type->id }}">{{ $type->title }} · {{ $type->funding_mode }}</option>@endforeach</select></label><label class="text-sm font-semibold">Cadence<select name="cadence" class="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3"><option value="weekly">Weekly</option><option value="fortnightly">Every two weeks</option></select></label>
<label class="text-sm font-semibold">Start date<input type="date" name="start_date" required class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">End date (optional)<input type="date" name="end_date" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">Occurrence count (optional)<input type="number" name="occurrence_count" min="1" max="104" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">Preferred local time<input type="time" name="preferred_time" required class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">Timezone<input name="timezone" required value="{{ $student->preferred_timezone ?: 'Africa/Cairo' }}" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">Ambiguous daylight-saving time<select name="fold_policy" class="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3"><option value="reject">Block and review</option><option value="first">First occurrence</option><option value="second">Second occurrence</option></select></label><button class="min-h-11 self-end rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Save plan</button></form><p class="mt-4 text-xs text-slate-500">A plan reserves no slots or credits. Maximum 104 occurrences per plan; create a new plan when continuing beyond that limit.</p></section>
<x-recurring-plans :plans="$plans" />
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Recent occurrences</h2><p class="mt-1 text-xs text-slate-500">Latest 100 attempts. Blocked occurrences consume no credit; retry their number after reviewing the reason.</p><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-3">Plan / occurrence</th><th class="p-3">Local date</th><th class="p-3">Result</th><th class="p-3">Reason / booking</th></tr></thead><tbody>@forelse($occurrences as $occurrence)<tr class="border-t border-slate-100"><td class="p-3">#{{ $occurrence->recurring_lesson_plan_id }} / {{ $occurrence->sequence }}</td><td class="p-3">{{ $occurrence->local_date->toDateString() }}</td><td class="p-3">{{ $occurrence->status }}</td><td class="p-3">@if($occurrence->booking_id)<a class="font-semibold text-amber-800" href="{{ route('admin.bookings.show', $occurrence->booking_id) }}">Booking #{{ $occurrence->booking_id }} · {{ $occurrence->booking->status }}</a>@else{{ str_replace('_', ' ', $occurrence->reason_code ?? 'pending') }}@endif</td></tr>@empty<tr><td colspan="4" class="p-4 text-slate-500">No generation attempts yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="mb-2 text-xl font-bold">Student unavailability</h2><p class="mb-5 text-sm text-slate-600">These periods block new bookings and rescheduling for this student. Existing appointments stay visible; review those separately.</p><x-planning-period-form :action="route('admin.students.holidays.store', $student)" :timezone="$student->preferred_timezone ?: 'Africa/Cairo'" />
<div class="mt-6 space-y-3">@forelse($holidays as $holiday)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><p class="text-sm">{{ $holiday->starts_at_utc->setTimezone($holiday->timezone)->format('Y-m-d') }} through {{ $holiday->ends_at_utc->setTimezone($holiday->timezone)->subDay()->format('Y-m-d') }} · {{ $holiday->timezone }} · {{ $holiday->status }}</p>@if($holiday->status === 'active')<form method="POST" action="{{ route('admin.students.holidays.cancel', [$student, $holiday]) }}">@csrf<button class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm">Cancel period</button></form>@endif</div>@empty<p class="text-sm text-slate-500">No recorded periods.</p>@endforelse{{ $holidays->links() }}</div></section></div>
@endsection
