@php
    $videoCreateUrl = isset($privateStudent) ? route('admin.students.private-learning.video',['student'=>$privateStudent,'course'=>$course,'booking'=>$bookingId]) : route('admin.lms.videos.store',$course);
    $videoRefreshUrl = isset($privateStudent) ? route('admin.students.private-learning.edit',['student'=>$privateStudent,'course'=>$course,'booking'=>$bookingId]) : route('admin.lms.courses.edit',$course);
@endphp
<section class="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-xs sm:p-6">
    <div class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-bold">Protected video media</h2>@if(auth()->user()?->role==='super_admin')<a href="{{ route('admin.lms.video.settings') }}" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-700">Provider & protection settings</a>@endif</div>
    <p class="text-sm leading-6 text-slate-500">@if(isset($privateStudent))Upload your video to Bunny. Wait until it is Ready, then add it to this learning before sharing with the Student.@else Upload directly to Bunny, then choose ready media in a lesson Video block. Upload completion is followed by processing. Replacing or detaching a block keeps shared media and retained revisions.@endif</p>
    <form method="POST" action="{{ $videoCreateUrl }}" data-bunny-upload data-create-url="{{ $videoCreateUrl }}" data-version="{{ $course->lock_version }}" class="grid items-end gap-4 md:grid-cols-3">
        @csrf<x-lms.input label="Media label" name="label" id="video-upload-label" :required="true" maxlength="200"/>
        <label class="text-sm font-semibold text-slate-700">Video file<input name="video" type="file" accept="video/*" required class="mt-2 block min-h-11 w-full rounded-xl border border-slate-300 p-2 text-sm"></label>
        <x-lms.button tone="neutral">Upload video</x-lms.button>
        <div class="md:col-span-3"><progress data-upload-progress max="100" value="0" aria-label="Video upload progress" class="w-full"></progress><p data-upload-status role="status" class="mt-2 text-sm text-slate-500">No upload in progress.</p><button data-upload-pause type="button" hidden class="min-h-11 text-sm font-semibold text-amber-700">Pause upload</button><a data-upload-reload hidden href="{{ $videoRefreshUrl }}" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-700">Refresh media list</a></div>
    </form>
    @if(!isset($privateStudent))<details class="rounded-xl border border-slate-200 p-4"><summary class="min-h-11 cursor-pointer text-sm font-semibold">Attach a YouTube or external video asset</summary><form method="POST" action="{{ route('admin.lms.videos.external',$course) }}" class="mt-4 grid items-end gap-4 md:grid-cols-2">@csrf<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="request_key" value="{{ \Illuminate\Support\Str::uuid() }}"><x-lms.input label="Media label" name="label" id="video-external-label" :required="true" maxlength="200"/><label class="text-sm font-semibold">Provider<select name="provider" class="mt-2 block min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="youtube">YouTube</option><option value="external">Vimeo / direct external video</option></select></label><x-lms.input label="HTTPS video link" name="url" id="video-external-url" type="url" :required="true" maxlength="2000"/><x-lms.button tone="neutral">Attach external asset</x-lms.button><p class="text-xs text-slate-500 md:col-span-2">External video is controlled by its provider. Bunny protections do not apply to external assets.</p></form></details>@endif
    <div class="space-y-3">@foreach($videoAssets as $video)<article data-video-asset class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div class="min-w-0"><p dir="auto" class="break-words text-sm font-semibold">{{ $video->label }}</p><p data-media-state class="mt-1 text-xs capitalize text-slate-500">{{ str_replace('_',' ', $video->status) }}@if($video->duration_seconds) · {{ $video->duration_seconds }} seconds @endif</p></div>@if((int)$video->course_id===(int)$course->id)@if($video->status==='uploading' && $video->provider_video_id)<button type="button" data-upload-resume="{{ isset($privateStudent) ? route('admin.students.private-learning.video.upload',[$privateStudent,$course,$video]) : route('admin.lms.videos.upload',[$course,$video]) }}" data-asset-id="{{ $video->id }}" class="min-h-11 text-sm font-semibold text-amber-700">Resume upload</button>@endif<button type="button" data-media-check="{{ isset($privateStudent) ? route('admin.students.private-learning.video.status',[$privateStudent,$course,$video]) : route('admin.lms.videos.status',[$course,$video]) }}" class="min-h-11 text-sm font-semibold text-amber-700">Check status / references</button>@if(!isset($privateStudent))<form method="POST" action="{{ route('admin.lms.videos.destroy',[$course,$video]) }}" onsubmit="return confirm('Delete this remote media if no course or retained revision references it?');">@csrf @method('DELETE')<x-lms.button tone="danger">Delete unreferenced media</x-lms.button></form>@endif @endif</article>@endforeach</div>
    <p class="text-xs leading-5 text-slate-500">@if(isset($privateStudent))Processing or failed videos cannot be shared. If video creation is interrupted, check Bunny before trying again. Removing learning content keeps the original video.@else Server checks block deletion while any course draft, live block or retained revision references the video. Failed or interrupted creation is marked unconfirmed and requires review in Bunny; it is never automatically repeated. Large upload bytes do not pass through PHP.@endif</p>
</section>
