<?php

namespace App\Domains\Availability\Services;

use App\Domains\Booking\Exceptions\SlotUnavailableException;
use App\Domains\Booking\Models\SessionType;
use App\Domains\Timezone\Services\TimezoneService;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\Crypt;
use Throwable;

class SlotResolver
{
    private const SCHEDULING_RESOURCE = 'primary_tutor';

    public function __construct(
        protected AvailabilityService $availabilityService,
        protected TimezoneService $timezoneService,
    ) {}

    /**
     * Issue an expiring identity for a slot generated by the server.
     * The business date names the existing booking_calendar_locks resource.
     *
     * @param  array<string, mixed>  $slot
     */
    public function issue(SessionType $sessionType, array $slot, string $timezone, string $visitorToken): string
    {
        $this->timezoneService->validate($timezone);

        return Crypt::encryptString(json_encode([
            'version' => 1,
            'resource_id' => self::SCHEDULING_RESOURCE,
            'resource_date' => $slot['business_date'],
            'session_type_id' => $sessionType->id,
            'start_utc' => $slot['slot_start_utc'],
            'end_utc' => $slot['slot_end_utc'],
            'customer_date' => $slot['customer_date'],
            'customer_timezone' => $timezone,
            'visitor_token' => $visitorToken,
            'policy' => $this->policyFingerprint($slot),
            'expires_at' => now('UTC')->addMinutes(10)->getTimestamp(),
        ], JSON_THROW_ON_ERROR));
    }

    /**
     * Resolve a submitted identity against the currently generated server slots.
     * The hold service repeats collision checks inside its calendar lock transaction.
     *
     * @return array<string, mixed>
     */
    public function resolve(string $slotId, SessionType $sessionType, string $timezone, string $visitorToken): array
    {
        $this->timezoneService->validate($timezone);

        try {
            $identity = json_decode(Crypt::decryptString($slotId), true, 512, JSON_THROW_ON_ERROR);
        } catch (Throwable) {
            throw new SlotUnavailableException('This time slot is invalid or has expired. Please select it again.');
        }

        if (! is_array($identity)
            || ($identity['version'] ?? null) !== 1
            || ($identity['session_type_id'] ?? null) !== $sessionType->id
            || ($identity['resource_id'] ?? null) !== self::SCHEDULING_RESOURCE
            || ($identity['customer_timezone'] ?? null) !== $timezone
            || ! hash_equals($visitorToken, (string) ($identity['visitor_token'] ?? ''))
            || ! is_int($identity['expires_at'] ?? null)
            || $identity['expires_at'] <= now('UTC')->getTimestamp()
            || ! preg_match('/^\d{4}-\d{2}-\d{2}$/', (string) ($identity['customer_date'] ?? ''))
        ) {
            throw new SlotUnavailableException('This time slot is invalid or has expired. Please select it again.');
        }

        $customerDate = CarbonImmutable::createFromFormat('!Y-m-d', $identity['customer_date'], $timezone);
        if (! $customerDate || $customerDate->toDateString() !== $identity['customer_date']) {
            throw new SlotUnavailableException('This time slot is invalid or has expired. Please select it again.');
        }

        $available = $this->availabilityService->getAvailableSlotsGroupedByDate(
            sessionType: $sessionType,
            customerTimezone: $timezone,
            fromDate: $customerDate,
            toDate: $customerDate,
            currentVisitorToken: $visitorToken,
        );

        foreach ($available[$identity['customer_date']] ?? [] as $slot) {
            if ($slot['slot_start_utc'] === ($identity['start_utc'] ?? null)
                && $slot['slot_end_utc'] === ($identity['end_utc'] ?? null)
                && $slot['business_date'] === ($identity['resource_date'] ?? null)
                && hash_equals($this->policyFingerprint($slot), (string) ($identity['policy'] ?? ''))
            ) {
                return $slot;
            }
        }

        throw new SlotUnavailableException('This time slot is no longer available. Please choose another time.');
    }

    /** @param array<string, mixed> $slot */
    protected function policyFingerprint(array $slot): string
    {
        return hash('sha256', json_encode([
            $slot['duration_minutes'],
            $slot['buffer_minutes'],
            $slot['min_notice_hours'],
            $slot['max_horizon_days'],
        ], JSON_THROW_ON_ERROR));
    }
}
