<section id="student-learning" aria-labelledby="student-learning-title" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 id="student-learning-title" class="font-serif text-xl font-bold">Learning</h2><p class="mt-1 text-sm text-slate-600">Courses, personal learning and current review needs.</p></div><a href="{{ route('admin.students.learning.create',$student) }}" class="inline-flex min-h-11 items-center rounded-xl bg-amber-700 px-4 text-sm font-semibold text-white">Assign Learning</a></div>
    <p class="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{{ $learningProfile['review_needs']['quizzes'] }} quizzes awaiting manual review · {{ $learningProfile['review_needs']['assignments'] }} assignments awaiting review</p>
    <div class="grid gap-3 sm:grid-cols-2">@forelse($learningProfile['cards'] as $card)<article class="rounded-xl border border-slate-200 p-4"><h3 dir="auto" class="break-words font-semibold">{{ $card['course']->title }}</h3><p class="mt-2 text-sm text-slate-600">{{ $card['progress']['status'] }} · {{ $card['progress']['percent'] }}% complete</p><a href="{{ route('admin.lms.reviews.index',$card['course']) }}" class="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-amber-800">Review learning</a></article>@empty<p class="text-sm text-slate-500">No current courses.</p>@endforelse</div>
    <div class="space-y-3">@foreach($learningProfile['items'] as $item)@php($grant=$item['grant'])<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><h3 dir="auto" class="break-words font-semibold">{{ $item['title'] }}</h3><p class="mt-1 text-xs text-slate-500">{{ ucfirst($item['kind']) }} · {{ $item['group'] }}@if($item['booking_id']) · Session #{{ $item['booking_id'] }}@endif</p></div><a href="{{ route('admin.lms.reviews.index',$item['course']) }}" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-800">Progress & review</a></div><p class="mt-2 text-sm text-slate-600">{{ $item['assessment']??$item['state'] }}@if(!$item['assessment']) · {{ $item['progress']['percent'] }}% of required course lessons @endif</p><p class="mt-2 text-xs text-slate-500">Starts {{ $item['starts_at']->copy()->timezone($businessTz)->format('j M Y, H:i T') }} · @if($item['expires_at'])Expires {{ $item['expires_at']->copy()->timezone($businessTz)->format('j M Y, H:i T') }}@else No scheduled expiry @endif</p>@if($item['reason'])<p class="mt-2 text-xs text-slate-500">{{ $item['reason'] }}</p>@endif
    @if($grant->status==='active')<details class="mt-3"><summary class="min-h-11 cursor-pointer text-sm font-semibold text-amber-800">Manage access</summary><div class="mt-3 flex flex-wrap gap-3">
        <form method="POST" action="{{ route('admin.students.learning.change',[$student,$grant]) }}" class="flex flex-wrap items-end gap-3">@csrf @method('PATCH')<input type="hidden" name="version" value="{{ $grant->lock_version }}"><input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><label class="text-xs font-semibold" for="grant-end-{{ $grant->id }}">New expiry ({{ $businessTz }})<input id="grant-end-{{ $grant->id }}" type="datetime-local" name="expires_local" required class="mt-2 block min-h-11 rounded-lg border border-slate-300 px-3"></label><x-lms.button name="action" :value="$grant->expires_at?'extend':'set_expiration'" tone="neutral">{{ $grant->expires_at?'Extend access':'Set expiry' }}</x-lms.button></form>
        @if($grant->expires_at)<form method="POST" action="{{ route('admin.students.learning.change',[$student,$grant]) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="remove_expiration"><input type="hidden" name="version" value="{{ $grant->lock_version }}"><input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><x-lms.button tone="neutral">Remove expiry</x-lms.button></form>@endif
        <form method="POST" action="{{ route('admin.students.learning.change',[$student,$grant]) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="revoke"><input type="hidden" name="version" value="{{ $grant->lock_version }}"><input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><x-lms.button tone="danger">Revoke access</x-lms.button></form>
    </div></details>@endif</article>@endforeach</div>
    @if($learningProfile['drafts']->isNotEmpty())<div class="space-y-2"><h3 class="font-semibold">Private drafts</h3>@foreach($learningProfile['drafts'] as $draft)<a href="{{ route('admin.students.private-learning.edit',[$student,$draft]) }}" class="block min-h-11 rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-amber-800" dir="auto">{{ $draft->title }} · Continue preparing</a>@endforeach</div>@endif
    @if($learningProfile['resources']->isNotEmpty())<div class="space-y-3"><h3 class="font-semibold">Assigned Resources</h3>@foreach($learningProfile['resources'] as $resource)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><p class="text-sm" dir="auto">{{ $resource->resource->title }} · {{ $resource->reviewed_at?'Reviewed':'New' }}</p><form method="POST" action="{{ route('admin.students.learning.resources.withdraw',[$student,$resource]) }}">@csrf @method('DELETE')<x-lms.button tone="danger">Withdraw sharing</x-lms.button></form></div>@endforeach</div>@endif
    <p class="text-xs text-slate-500">Tutor notes and Homework stay in their existing areas. <a class="inline-flex min-h-11 items-center font-semibold text-amber-800 underline" href="{{ route('admin.students.teaching',$student) }}#teaching-plan">Open learning plans & Homework</a></p>
</section>
@include('components.learning-timeline',['timelineId'=>'student-learning-timeline','timelineItems'=>$learningProfile['timeline'],'timelineTimezone'=>$businessTz])
