@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-5xl space-y-6">
    <a href="{{ route('admin.students.show',$student) }}#student-learning" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-800">← {{ $student->name }} · Learning</a>
    <header><h1 class="font-serif text-3xl font-bold text-slate-900">{{ $bookingId ? 'Assign Follow-up Learning' : 'Assign Learning' }}</h1><p class="mt-2 text-slate-600">For {{ $student->name }}@if($bookingId) · Tutoring session #{{ $bookingId }}@endif</p></header>
    @if(session('success'))<p role="status" class="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('success') }}</p>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-rose-50 p-4 text-sm text-rose-900"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <nav aria-label="Assignment choices" class="flex flex-wrap gap-2"><a href="#existing-learning" class="min-h-11 rounded-full border border-slate-200 bg-white px-4 py-3 text-sm font-semibold">Assign existing learning</a><a href="#create-private" class="min-h-11 rounded-full border border-slate-200 bg-white px-4 py-3 text-sm font-semibold">Create for this Student</a>@if($bookingId)<a href="{{ route('admin.bookings.show',$bookingId) }}" class="min-h-11 px-4 py-3 text-sm text-slate-600">Skip · Return to session</a>@endif</nav>
    <section id="existing-learning" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
        <h2 class="text-xl font-semibold">Assign existing learning</h2>
        <form method="GET" class="flex flex-wrap items-end gap-3"><input type="hidden" name="booking" value="{{ $bookingId }}"><label for="learning-search" class="flex-1 text-sm font-semibold">Find learning<input id="learning-search" name="q" value="{{ $filters['q']??'' }}" maxlength="100" placeholder="Course, lesson or Resource title" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><x-lms.button tone="neutral">Search</x-lms.button></form>
        <form method="POST" action="{{ route('admin.students.learning.store',$student) }}" x-data="{kind:@js(old('kind','course'))}" class="space-y-5">
            @csrf<input type="hidden" name="request_key" value="{{ old('request_key',(string)\Illuminate\Support\Str::uuid()) }}">
            <label for="existing-kind" class="block text-sm font-semibold">Learning type<select id="existing-kind" name="kind" x-model="kind" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3">@foreach(['course'=>'Course','lesson'=>'Lesson','resource'=>'Resource','quiz'=>'Quiz','assignment'=>'Assignment'] as $value=>$label)<option value="{{ $value }}" @selected(old('kind','course')===$value)>{{ $label }}</option>@endforeach</select></label>
            @foreach(['course'=>$courses,'lesson'=>$lessons,'resource'=>$resources,'quiz'=>$assessments->where('kind','quiz'),'assignment'=>$assessments->where('kind','assignment')] as $kind=>$choices)
                <label x-show="kind===@js($kind)" for="target-{{ $kind }}" class="block text-sm font-semibold">Choose {{ $kind }}<select id="target-{{ $kind }}" name="target_id" :disabled="kind!==@js($kind)" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3" :required="kind===@js($kind)"><option value="">Select learning</option>@foreach($choices as $choice)<option value="{{ $choice->id }}" @selected((int)old('target_id')===(int)$choice->id)>{{ $choice->title ?? $choice->payload['title'] ?? ucfirst($kind) }}@if($kind==='lesson') · {{ $choice->course->title }}@elseif(in_array($kind,['quiz','assignment'],true)) · {{ $choice->lesson->title }}@endif</option>@endforeach</select></label>
            @endforeach
            <label for="existing-session" class="block text-sm font-semibold">Tutoring session (optional)<select id="existing-session" name="booking_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">No session relationship</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected((int)old('booking_id',$bookingId)===(int)$booking->id)>#{{ $booking->id }} · {{ $booking->start_at_utc->copy()->timezone($businessTz)->format('j M Y, H:i') }} · {{ $booking->studentStatusLabel() }}</option>@endforeach</select></label>
            <label for="existing-instructions" class="block text-sm font-semibold">Instructions for this Student<textarea id="existing-instructions" dir="auto" name="instructions" maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 p-3">{{ old('instructions') }}</textarea></label>
            @include('admin.students._learning-availability',['prefix'=>'existing','resourceChoice'=>true])
            <details class="rounded-xl bg-slate-50 p-4"><summary class="cursor-pointer text-sm font-semibold">Also assign existing catalog learning or Resource to other Students</summary><p class="mt-3 text-xs text-slate-600">Up to 25 Students including this Student, with individual access. Leave the session blank. Private learning stays with its owner.</p><label for="bulk-students" class="mt-3 block text-sm">Additional Students<select id="bulk-students" name="extra_student_ids[]" multiple size="5" class="mt-2 w-full rounded-xl border border-slate-300 p-3">@foreach($students as $other)<option value="{{ $other->id }}">{{ $other->name }}</option>@endforeach</select></label></details>
            <x-lms.button>Assign learning</x-lms.button>
        </form>
    </section>
    <section id="create-private" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
        <div><h2 class="text-xl font-semibold">Create for this Student</h2><p class="mt-2 text-sm text-slate-600">A small private item, protected video, quiz or assignment. Add attachments, Resources and links in the editor.</p></div>
        <form method="POST" action="{{ route('admin.students.private-learning.store',$student) }}" class="space-y-5" x-data="{kind:@js(in_array(old('kind'),['rich_text','video','quiz','assignment'],true)?old('kind'):'rich_text')}">
            @csrf<input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}">
            <x-lms.input label="Title" name="title" id="private-title" :value="old('title')" :required="true" maxlength="200"/>
            <label for="private-kind" class="block text-sm font-semibold">Start with<select id="private-kind" name="kind" x-model="kind" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="rich_text">Private learning item</option><option value="video">Private Bunny video</option><option value="quiz">Private quiz</option><option value="assignment">Private assignment</option></select></label>
            <label for="private-instructions" class="block text-sm font-semibold">Instructions for this Student<textarea id="private-instructions" name="instructions" dir="auto" maxlength="5000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 p-3">{{ old('instructions') }}</textarea></label>
            <div x-show="kind==='rich_text'"><x-lms.rich-text-editor id="private-body" :value="old('html','')"/></div>
            @include('admin.lms.courses._assessment',['payload'=>[]])
            <label for="private-session" class="block text-sm font-semibold">Tutoring session (optional)<select id="private-session" name="booking_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">No session relationship</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected((int)old('booking_id',$bookingId)===(int)$booking->id)>#{{ $booking->id }} · {{ $booking->start_at_utc->copy()->timezone($businessTz)->format('j M Y, H:i') }} · {{ $booking->studentStatusLabel() }}</option>@endforeach</select></label>
            @include('admin.students._learning-availability',['prefix'=>'private','resourceChoice'=>false])
            <div class="flex flex-wrap gap-3"><x-lms.button name="share_now" value="0" tone="neutral">Create draft & add content</x-lms.button><button x-show="kind!=='video'" type="submit" name="share_now" value="1" class="min-h-11 rounded-xl bg-amber-700 px-5 text-sm font-semibold text-white">Create & share</button></div>
            <p x-show="kind==='video'" class="text-xs text-slate-500">Create the draft, upload directly to Bunny, check Ready, then share. Private protection and the {{ $defaultVideoThreshold }}% watch requirement apply by default.</p>
        </form>
    </section>
</div>
@endsection
