@extends('layouts.admin')
@section('content')
@php($blockAction=route('admin.students.private-learning.update',[$student,$course]))
@php($allowedKinds=['rich_text'=>'Text','image'=>'Image','file'=>'Private attachment','resource'=>'Resource','external_link'=>'Learning link','video'=>'Protected Bunny video','quiz'=>'Quiz','assignment'=>'Assignment'])
<div class="mx-auto max-w-5xl space-y-6">
    <header class="flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('admin.students.show',$student) }}#student-learning" class="inline-flex min-h-11 items-center text-sm font-semibold text-amber-800">← {{ $student->name }} · Learning</a><h1 class="mt-2 font-serif text-3xl font-bold" dir="auto">{{ $graph['title'] }}</h1><p class="mt-2 text-sm text-slate-600">Private learning for {{ $student->name }} · {{ ucfirst($course->status) }}</p></div><a href="#share-private" class="min-h-11 rounded-xl bg-amber-700 px-5 py-3 text-sm font-semibold text-white">Share with Student</a></header>
    @if(session('success'))<p role="status" class="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('success') }}</p>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-rose-50 p-4 text-sm text-rose-900"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <p class="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Save each form as you work. Drafts are private until you share. Existing shared content stays available while you prepare changes.</p>
    <form method="POST" action="{{ $blockAction }}" class="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-5">@csrf @method('PATCH')<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="operation" value="metadata"><input type="hidden" name="booking_id" value="{{ $bookingId }}"><div class="flex-1"><x-lms.input name="title" label="Learning title" id="private-edit-title" :value="$graph['title']" :required="true" maxlength="200"/></div><x-lms.button tone="neutral">Save title</x-lms.button></form>
    @include('admin.lms.courses._videos',['privateStudent'=>$student])
    <section class="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 class="text-xl font-semibold">Attachments</h2><form method="POST" action="{{ route('admin.students.private-learning.upload',[$student,$course]) }}" enctype="multipart/form-data" class="grid gap-4 sm:grid-cols-3">@csrf<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="booking_id" value="{{ $bookingId }}"><label for="private-file-kind" class="text-sm font-semibold">Type<select id="private-file-kind" name="kind" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="file">PDF / file / audio</option><option value="image">Image</option></select></label><label for="private-file" class="text-sm font-semibold">File<input id="private-file" name="file" type="file" required accept=".jpg,.jpeg,.png,.webp,.pdf,.zip,.doc,.docx,.mp3,.wav,.m4a" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 p-2"></label><x-lms.button tone="neutral">Upload attachment</x-lms.button></form><p class="text-xs text-slate-500">Images up to 10 MB; files up to 50 MB. Select uploaded attachments or published Resources in the content forms.</p></section>
    <section class="space-y-4" aria-labelledby="private-content"><h2 id="private-content" class="text-xl font-semibold">Learning content</h2>@foreach($lesson['blocks'] as $block)@if($block['status']==='ready')<details class="rounded-2xl border border-slate-200 bg-white p-5"><summary class="min-h-11 cursor-pointer font-semibold">{{ $block['payload']['title']??$allowedKinds[$block['kind']]??'Content' }} · {{ $loop->iteration }}</summary><div class="mt-4">@include('admin.lms.courses._block-form')</div><form method="POST" action="{{ $blockAction }}" class="mt-3">@csrf @method('PATCH')<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="operation" value="remove_block"><input type="hidden" name="key" value="{{ $block['key'] }}"><input type="hidden" name="booking_id" value="{{ $bookingId }}"><x-lms.button tone="danger">Remove content from draft</x-lms.button></form></details>@endif@endforeach<details class="rounded-2xl border border-slate-200 bg-white p-5" @if(!collect($lesson['blocks'])->contains('status','ready')) open @endif><summary class="min-h-11 cursor-pointer font-semibold text-amber-800">Add text, video, file, Resource, link, quiz or assignment</summary><div class="mt-4">@include('admin.lms.courses._block-form',['block'=>null])</div></details></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 class="text-xl font-semibold">Completion</h2><p class="mt-2 text-sm text-slate-600">All selected requirements must be met. This uses the same completion rules as other learning.</p><form method="POST" action="{{ $blockAction }}" class="mt-4 space-y-4">@csrf @method('PATCH')<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="operation" value="learning"><input type="hidden" name="key" value="{{ $lesson['key'] }}"><input type="hidden" name="booking_id" value="{{ $bookingId }}"><input type="hidden" name="required" value="0"><label class="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name="required" value="1" @checked($lesson['learning_rules']['required']??true)>Required for completion</label><fieldset><legend class="text-sm font-semibold">Requirements</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach(['manual'=>'Student marks complete','video'=>'Watch Bunny videos','quiz_complete'=>'Complete quizzes','quiz_pass'=>'Pass quizzes','assignment_submit'=>'Submit assignments','assignment_approve'=>'Assignments approved'] as $method=>$label)<label class="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name="methods[]" value="{{ $method }}" @checked(in_array($method,$lesson['learning_rules']['methods']??['manual'],true))>{{ $label }}</label>@endforeach</div></fieldset><x-lms.input name="video_threshold" id="private-threshold" label="Video watched threshold (%)" type="number" min="1" max="100" :value="$lesson['learning_rules']['video_threshold']??95"/><x-lms.button tone="neutral">Save completion rules</x-lms.button></form></section>
    <section id="share-private" class="space-y-5 rounded-2xl border border-amber-200 bg-white p-5 sm:p-7"><h2 class="text-xl font-semibold">Share with {{ $student->name }}</h2><form method="POST" action="{{ route('admin.students.private-learning.share',[$student,$course]) }}" class="space-y-5">@csrf<input type="hidden" name="version" value="{{ $course->lock_version }}"><input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><label for="share-session" class="block text-sm font-semibold">Tutoring session (optional)<select id="share-session" name="booking_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">No session relationship</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected((int)$bookingId===(int)$booking->id)>#{{ $booking->id }} · {{ $booking->start_at_utc->copy()->timezone($businessTz)->format('j M Y, H:i') }} · {{ $booking->studentStatusLabel() }}</option>@endforeach</select></label><label for="share-instructions" class="block text-sm font-semibold">Additional instructions (optional)<textarea id="share-instructions" name="instructions" dir="auto" rows="3" maxlength="5000" class="mt-2 w-full rounded-xl border border-slate-300 p-3">{{ old('instructions') }}</textarea></label>@include('admin.students._learning-availability',['prefix'=>'share','availability'=>$graph['access'],'resourceChoice'=>false])<x-lms.button>Publish & share private learning</x-lms.button><p class="text-xs text-slate-500">Only this Student receives access. Video processing and content validation must pass before sharing.</p></form></section>
</div>
@endsection
