@extends('layouts.admin')
@section('content')
@php
$input='block w-full rounded-xl border border-slate-300 bg-slate-50 p-2.5 text-sm text-slate-900';
$button='rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700';
$card='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm';
@endphp
<div class="mx-auto max-w-6xl space-y-6">
<div><h1 class="text-3xl font-bold text-slate-900">Telegram Bots</h1><p class="mt-2 text-slate-500">Manage notification bots, destinations, alert rules and delivery history. The public footer Telegram link is configured separately.</p></div>
@if(session('success'))<div role="status" class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if(session('error'))<div role="alert" class="rounded-xl bg-rose-50 p-4 text-rose-800">{{ session('error') }}</div>@endif
@if($errors->any())<div role="alert" class="rounded-xl bg-rose-50 p-4 text-rose-800"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<nav aria-label="Telegram management" class="flex flex-wrap gap-2">@foreach(['overview'=>'Overview','bots'=>'Bots','destinations'=>'Destinations','rules'=>'Alert rules','commands'=>'Commands','history'=>'Delivery history'] as $key=>$label)<a class="rounded-xl px-4 py-2 {{ $tab===$key?'bg-slate-900 text-white':'bg-white text-slate-600' }}" href="{{ route('admin.telegram.index',['tab'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
@if($tab==='overview')
<section class="{{ $card }}"><h2 class="text-xl font-semibold">Automation controls</h2><form class="mt-4 flex flex-wrap items-center gap-5" method="POST" action="{{ route('admin.telegram.global') }}">@csrf<label><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(\App\Domains\CMS\Models\Setting::get('telegram.automation_enabled',false))> Enable automated alerts</label><label><input type="checkbox" name="commands_enabled" value="1" @checked(\App\Domains\CMS\Models\Setting::get('telegram.commands_enabled',false))> Enable interactive commands globally</label><button class="{{ $button }}">Save switches</button></form><p class="mt-4 text-sm text-slate-500">Each bot, destination and rule also has its own switch. Commands require an enabled bot, an enabled allowed chat and an explicitly allowed Telegram user.</p></section>
<section class="{{ $card }}"><h2 class="text-xl font-semibold">Runtime status</h2><dl class="mt-4 grid gap-4 sm:grid-cols-3">@foreach(['last_scheduler_run_at'=>'Scheduler heartbeat','telegram.last_tick_at'=>'Telegram monitor','telegram.last_watchdog_run_at'=>'Independent watchdog'] as $key=>$label)<div><dt class="text-sm text-slate-500">{{ $label }}</dt><dd class="mt-1 break-words">{{ \App\Domains\CMS\Models\Setting::get($key,'Never observed') ?: 'Never observed' }}</dd></div>@endforeach<div><dt class="text-sm text-slate-500">Queue worker heartbeat</dt><dd>{{ \Illuminate\Support\Facades\Cache::get('queue_worker_heartbeat_at','Never observed') }}</dd></div></dl><p class="mt-4 text-sm text-amber-800">Alerts need the scheduler and database queue worker. Scheduler-failure alerts need a separate host cron running telegram:watchdog; the Laravel scheduler cannot detect its own failure. An outage of this host needs an external monitor.</p></section>
<section class="{{ $card }}"><h2 class="text-xl font-semibold">{{ $bots->count() }} bots · {{ $destinations->count() }} destinations · {{ $rules->count() }} rules</h2><p class="mt-2 text-sm text-slate-500">Existing reminders are imported once, preserving their token, recipients and countdown windows. Shared destinations default to limited detail; personal detail must be selected explicitly.</p></section>
@endif
@if($tab==='bots' || $tab==='commands')
@foreach($bots->all() as $bot)
<section class="{{ $card }}"><form class="space-y-4" method="POST" action="{{ route('admin.telegram.bot',$bot) }}">@csrf
<h2 class="text-xl font-semibold">{{ $bot->name }}</h2><div class="grid gap-4 md:grid-cols-2"><label>Name<input class="{{ $input }}" name="name" value="{{ $bot->name }}" required></label><label>Replace token (leave blank to keep it)<input class="{{ $input }}" type="password" name="token" autocomplete="new-password" placeholder="•••••••• — stored encrypted"></label></div>
<label class="inline-flex items-center gap-2"><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked($bot->enabled)> Bot enabled</label>
<label class="ml-4 inline-flex items-center gap-2"><input type="checkbox" name="commands_enabled" value="1" @checked($bot->commands_enabled)> Commands enabled for this bot</label>
<div class="flex flex-wrap gap-4">@foreach(['today','tomorrow','student','stats'] as $command)<label><input type="checkbox" name="commands[]" value="{{ $command }}" @checked(in_array($command,$bot->commands??[]))> /{{ $command }}</label>@endforeach</div>
<p class="text-sm text-slate-500">Last successful delivery: {{ $bot->last_success_at ? app(\App\Domains\Timezone\Services\TimezoneDisplayService::class)->administratorDateTime($bot->last_success_at) : 'None' }} · Last failure: {{ $bot->failure_code ?: 'None' }}. Tokens are never returned to the page.</p><button class="{{ $button }}">Save bot</button></form></section>
@endforeach
@if($tab==='bots')<section class="{{ $card }}"><h2 class="text-xl font-semibold">Add bot</h2><form method="POST" action="{{ route('admin.telegram.bot') }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf<label>Friendly name<input class="{{ $input }}" name="name" required></label><label>Bot token<input class="{{ $input }}" type="password" name="token" autocomplete="new-password" required></label><label><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" checked> Enabled</label><div><button class="{{ $button }}">Add bot</button></div></form></section>@endif
@if($tab==='commands')<section class="{{ $card }}"><h2 class="text-xl font-semibold">Private command access</h2><p class="mt-2 text-sm text-slate-600">Enable commands globally and for a bot, then allow Telegram user IDs on its destination. Both the chat and user must match. /student requires personal detail and resolves names only when exactly one student matches. /stats accepts 7d or 30d. Polling runs independently with a persisted offset and a lock; it must be configured on the host.</p></section>@endif
@endif
@if($tab==='destinations')
@foreach($destinations->all() as $destination)
<section class="{{ $card }}"><form method="POST" action="{{ route('admin.telegram.destination',$destination) }}" class="space-y-4">@csrf<h2 class="text-xl font-semibold">{{ $destination->name }} · {{ $destination->bot->name }}</h2><input type="hidden" name="telegram_bot_id" value="{{ $destination->telegram_bot_id }}">@include('admin.telegram.destination-fields',['destination'=>$destination])<button class="{{ $button }}">Save destination</button></form><form class="mt-4" method="POST" action="{{ route('admin.telegram.test',$destination) }}">@csrf<button class="rounded-xl border border-slate-300 px-4 py-2 text-sm">Send labeled TEST to this destination</button></form></section>
@endforeach
<section class="{{ $card }}"><h2 class="text-xl font-semibold">Add destination</h2><form class="mt-4 space-y-4" method="POST" action="{{ route('admin.telegram.destination') }}">@csrf<label>Bot<select class="{{ $input }}" name="telegram_bot_id" required>@foreach($bots as $bot)<option value="{{ $bot->id }}">{{ $bot->name }}</option>@endforeach</select></label>@include('admin.telegram.destination-fields',['destination'=>null])<button class="{{ $button }}">Add destination</button></form></section>
@endif
@if($tab==='rules')
<section class="{{ $card }}"><h2 class="text-xl font-semibold">Configured alerts</h2><div class="mt-4 divide-y divide-slate-100">@forelse($rules->groupBy(fn($r)=>$catalog[$r->trigger]['group']) as $group=>$items)<h3 class="pt-4 font-semibold text-slate-500">{{ $group }}</h3>@foreach($items as $rule)<div class="flex flex-wrap items-center justify-between gap-3 py-3"><div>{{ $rule->name }} <span class="text-sm text-slate-500">{{ $rule->enabled?'Enabled':'Disabled' }} · {{ $rule->bot->name }} · {{ $rule->destinations->count() }} destinations</span></div><a class="text-amber-700 underline" href="{{ route('admin.telegram.index',['tab'=>'rules','edit'=>$rule->id]) }}">Edit rule</a>@if($rule->mode==='on_demand')<form method="POST" action="{{ route('admin.telegram.run',$rule) }}">@csrf<button class="{{ $button }}">Run report</button></form>@endif</div>@endforeach @empty<p class="text-slate-500">No rules configured. Add an alert below.</p>@endforelse</div></section>
<section class="{{ $card }}" x-data="{ trigger: {{ \Illuminate\Support\Js::from(old('trigger',$editingRule?->trigger ?? 'booking_created')) }}, bot: {{ \Illuminate\Support\Js::from((string)old('telegram_bot_id',$editingRule?->telegram_bot_id ?? $bots->first()?->id ?? '')) }}, mode: {{ \Illuminate\Support\Js::from(old('mode',$editingRule?->mode ?? 'instant')) }}, minutes: {{ old('minutes',$editingRule?->minutes??60) }}, threshold: {{ old('threshold',$editingRule?->threshold??1) }}, template: {{ \Illuminate\Support\Js::from(old('template',$editingRule?->template ?? $catalog['booking_created']['template'])) }}, catalog: {{ \Illuminate\Support\Js::from($catalog) }} }">
<h2 class="text-xl font-semibold">{{ $editingRule?'Edit alert rule':'Add alert rule' }}</h2>
<form class="mt-4 space-y-4" method="POST" action="{{ route('admin.telegram.rule',$editingRule) }}">@csrf
<div class="grid gap-4 md:grid-cols-2"><label>Rule name<input class="{{ $input }}" name="name" value="{{ old('name',$editingRule?->name) }}" required></label><label>Alert type<select class="{{ $input }}" name="trigger" x-model="trigger" @change="template=catalog[trigger].template; mode=catalog[trigger].modes[0]; minutes=catalog[trigger].defaults.minutes; threshold=catalog[trigger].defaults.threshold">@foreach($catalog as $key=>$definition)<option value="{{ $key }}">{{ $definition['group'] }} — {{ $definition['label'] }}</option>@endforeach</select></label>
<label>Bot<select class="{{ $input }}" name="telegram_bot_id" x-model="bot" required>@foreach($bots as $bot)<option value="{{ $bot->id }}">{{ $bot->name }}</option>@endforeach</select></label><label>Delivery mode<select class="{{ $input }}" name="mode" x-model="mode"><template x-for="value in catalog[trigger].modes" :key="value"><option :value="value" x-text="value"></option></template></select></label></div>
<fieldset><legend class="font-semibold">Destinations for this bot</legend><div class="mt-2 flex flex-wrap gap-4">@foreach($destinations as $destination)<label x-show="bot === '{{ $destination->telegram_bot_id }}'"><input type="checkbox" name="destinations[]" value="{{ $destination->id }}" :disabled="bot !== '{{ $destination->telegram_bot_id }}'" @checked(in_array($destination->id,old('destinations',$editingRule?->destinations->pluck('id')->all()??[])))> {{ $destination->name }} ({{ $destination->detail_level }})</label>@endforeach</div></fieldset>
<div class="grid gap-4 md:grid-cols-3"><label>Priority<select name="priority" class="{{ $input }}">@foreach(['normal','low','critical'] as $priority)<option @selected(old('priority',$editingRule?->priority)===$priority)>{{ $priority }}</option>@endforeach</select></label><label>Cooldown (minutes)<input name="cooldown_minutes" type="number" min="0" class="{{ $input }}" value="{{ old('cooldown_minutes',$editingRule?->cooldown_minutes??1440) }}" required></label><label x-show="mode==='delayed' || ['session_reminder','missing_form','scheduler_stale','queue_stale','maintenance_duration'].includes(trigger)"><span x-text="['session_reminder','missing_form'].includes(trigger)?'Minutes before lesson':(['scheduler_stale','queue_stale','maintenance_duration'].includes(trigger)?'Duration threshold (minutes)':'Delay (minutes)')"></span><input class="{{ $input }}" type="number" name="minutes" x-model="minutes" min="1" value="{{ old('minutes',$editingRule?->minutes??60) }}" required></label><label x-show="['low_credits','package_expiring','traffic_spike'].includes(trigger)"><span x-text="trigger==='low_credits'?'Credits at or below':(trigger==='package_expiring'?'Days before expiry':'Unique visitor threshold')"></span><input class="{{ $input }}" type="number" name="threshold" x-model="threshold" min="0" value="{{ old('threshold',$editingRule?->threshold??1) }}" required></label><label x-show="trigger==='traffic_spike'">Traffic window (minutes)<input class="{{ $input }}" type="number" name="window_minutes" value="{{ old('window_minutes',$editingRule?->window_minutes??60) }}" min="1" max="1440" required></label><label x-show="mode==='scheduled'">Daily send time (business timezone)<input class="{{ $input }}" type="time" name="send_time" value="{{ old('send_time',$editingRule?->send_time??'08:00') }}" required></label>
<label>Quiet hours start<input class="{{ $input }}" type="time" name="quiet_start" value="{{ old('quiet_start',$editingRule?->quiet_start) }}"></label><label>Quiet hours end<input class="{{ $input }}" type="time" name="quiet_end" value="{{ old('quiet_end',$editingRule?->quiet_end) }}"></label></div>
<p class="text-sm text-slate-500">Normal and low priority messages wait until quiet hours end. Critical priority bypasses quiet hours. Threshold alerts use a persistent cooldown for the affected package or system condition.</p>
<fieldset x-show="trigger==='business_digest'"><legend>Digest sections</legend><div class="mt-2 flex flex-wrap gap-4">@foreach(['bookings','students','resources','system','analytics'] as $section)<label><input type="checkbox" name="sections[]" value="{{ $section }}" @checked(in_array($section,old('sections',$editingRule?->sections??['bookings','students','resources','system'])))> {{ ucfirst($section) }}</label>@endforeach</div></fieldset>
<fieldset class="rounded-xl border border-slate-200 p-4"><legend class="font-semibold">Optional conditions (blank matches all)</legend><div class="grid gap-3 sm:grid-cols-2"><label>Student<select class="{{ $input }}" name="conditions[_student_id]"><option value="">All students</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected((string)old('conditions._student_id',$editingRule?->conditions['_student_id']??'')===(string)$student->id)>{{ $student->name }}</option>@endforeach</select></label><label>Lesson format<select class="{{ $input }}" name="conditions[_session_type_id]"><option value="">All formats</option>@foreach($sessionTypes as $sessionType)<option value="{{ $sessionType->id }}" @selected((string)old('conditions._session_type_id',$editingRule?->conditions['_session_type_id']??'')===(string)$sessionType->id)>{{ $sessionType->title }}</option>@endforeach</select></label><label>Country code (resource/booking alerts)<input class="{{ $input }}" name="conditions[country]" maxlength="2" value="{{ old('conditions.country',$editingRule?->conditions['country']??'') }}"></label><label>Source (resource/booking/traffic alerts)<input class="{{ $input }}" name="conditions[source]" value="{{ old('conditions.source',$editingRule?->conditions['source']??'') }}"></label></div><p class="mt-2 text-xs text-slate-500">A condition with no matching field on the alert will prevent sending. Leave unrelated fields blank.</p></fieldset>
<label class="block">Message template<textarea class="{{ $input }} min-h-56" name="template" x-model="template" required></textarea></label><p class="text-sm text-slate-600">Allowed placeholders: <span x-text="catalog[trigger].fields.map(field=>'{'+field+'}').join(' · ')"></span></p><p class="text-sm text-slate-500">Templates are plain text. Names, contacts, student local time and meeting links are hidden for limited-detail destinations. Long messages are split safely.</p>
<label><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(old('enabled',$editingRule?->enabled??true))> Rule enabled</label><div class="flex gap-3"><button class="{{ $button }}">Save alert rule</button><button class="rounded-xl border border-slate-300 px-4 py-2 text-sm" formaction="{{ route('admin.telegram.preview') }}">Preview with sample data</button></div>
</form>@if(session('preview'))<h3 class="mt-5 font-semibold">Sample preview</h3><pre class="mt-2 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 text-sm">{{ session('preview') }}</pre>@endif</section>
@endif
@if($tab==='history')
<section class="{{ $card }}"><form method="GET" class="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><input type="hidden" name="tab" value="history">@foreach(['bot'=>$bots,'destination'=>$destinations,'rule'=>$rules] as $key=>$items)<label>{{ ucfirst($key) }}<select class="{{ $input }}" name="{{ $key }}"><option value="">All</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(request($key)==$item->id)>{{ $item->name }}</option>@endforeach</select></label>@endforeach<label>Status<select class="{{ $input }}" name="status"><option value="">All</option>@foreach(['pending','sending','sent','failed','uncertain','cancelled'] as $status)<option @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></label><label>Date (Business Time)<input class="{{ $input }}" type="date" name="date" value="{{ request('date') }}"></label><button class="{{ $button }} self-end">Filter</button></form><div class="mt-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Date (Business Time)','Bot / destination','Alert','Status','Attempts','Message IDs / reason'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($history as $delivery)<tr class="border-t border-slate-100"><td class="p-3">{{ app(\App\Domains\Timezone\Services\TimezoneDisplayService::class)->administratorDateTime($delivery->created_at) }}</td><td class="p-3">{{ $delivery->bot->name }} / {{ $delivery->destination->name }}</td><td class="p-3">{{ $delivery->rule?->name??$delivery->trigger }}</td><td class="p-3">{{ $delivery->status }}</td><td class="p-3">{{ $delivery->attempts }}</td><td class="p-3">{{ implode(', ',$delivery->message_ids??[]) }} {{ $delivery->failure_code }}</td></tr>@empty<tr><td colspan="6" class="p-6 text-slate-500">No matching deliveries.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $history->links() }}</div><p class="mt-4 text-sm text-slate-500">An uncertain outcome means Telegram may have accepted the request. It is not automatically resent. Delivery payloads are encrypted and excluded from this history.</p></section>
@endif
</div>
@endsection
