@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div><a class="text-sm font-semibold text-amber-800" href="{{ route('admin.students.show', $package->student_id) }}">← Student record</a><h1 class="mt-3 font-serif text-3xl font-bold">{{ $package->package_name }} · Purchase #{{ $package->id }}</h1><p class="mt-2 text-sm text-slate-600">{{ $package->student?->name ?? 'Historical student' }} · Final price {{ $package->final_price }} {{ $package->currency }} · Due {{ $summary['balance_due'] }} · Overpaid {{ $summary['overpaid'] }}</p><a class="mt-3 inline-block font-semibold text-amber-800" href="{{ route('admin.statements.show', $package) }}">Statement & receipts →</a></div>
@if($originRenewal)<p class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Renewed on {{ $originRenewal->renewal_date->toDateString() }} from <a class="font-semibold text-amber-800" href="{{ route('admin.packages.lifecycle', $originRenewal->previous_package_id) }}">purchase #{{ $originRenewal->previous_package_id }}</a>.</p>@endif
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Expected installments</h2><p class="mt-2 text-sm text-slate-600">Forecasts cover the full final price. Actual net payments satisfy them in due-date order. Refunds reopen amounts due; forecast rows never create payments. Due dates use {{ $timezone }}.</p>
@if(count($installments))<div class="mt-5 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-3">Due date</th><th class="p-3">Expected</th><th class="p-3">Paid toward forecast</th><th class="p-3">Due</th><th class="p-3">Computed status</th></tr></thead><tbody>@foreach($installments as $row)<tr class="border-t border-slate-100"><td class="p-3">{{ $row['due_date'] }}</td><td class="p-3">{{ $row['expected_amount'] }}</td><td class="p-3">{{ $row['paid'] }}</td><td class="p-3">{{ $row['due'] }}</td><td class="p-3">{{ str_replace('_', ' ', $row['status']) }}</td></tr>@endforeach</tbody></table></div><form method="POST" action="{{ route('admin.packages.installments.void', $package) }}" class="mt-4">@csrf<button class="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold">Void forecast schedule</button></form>
@else
<form method="POST" action="{{ route('admin.packages.installments', $package) }}" class="mt-5 space-y-3" x-data="{ visible: {{ max(2, count(old('installments', []))) }} }">
    @csrf
    <input type="hidden" name="idempotency_key" value="{{ \Illuminate\Support\Str::uuid() }}">
    @for($i = 0; $i < 12; $i++)
    <div x-show="visible > {{ $i }}" @if($i >= max(2, count(old('installments', [])))) style="display: none;" @endif class="grid gap-3 sm:grid-cols-2">
        <label class="text-xs font-semibold">Installment {{ $i + 1 }} amount<input type="number" min="0.01" step="0.01" name="installments[{{ $i }}][expected_amount]" value="{{ old('installments.'.$i.'.expected_amount') }}" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label>
        <label class="text-xs font-semibold">Due date<input type="date" name="installments[{{ $i }}][due_date]" value="{{ old('installments.'.$i.'.due_date') }}" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label>
    </div>
    @endfor
    <button type="button" x-show="visible < 12" @click="visible++" class="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold">Add another installment</button>
    <p class="text-xs text-slate-500">Leave unused rows blank. One immutable schedule per purchase; a voided forecast stays in history.</p>
    <button class="min-h-11 rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Save expected schedule</button>
</form>
@endif</section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Renew as a new purchase</h2><p class="mt-2 text-sm text-slate-600">The previous purchase and its payments remain unchanged. A listed offering uses current catalog terms. Repeating a custom purchase preserves its price and typed quantity; set a new expiry if needed. No payment is recorded automatically.</p><form method="POST" action="{{ route('admin.packages.renew', $package) }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<input type="hidden" name="idempotency_key" value="{{ \Illuminate\Support\Str::uuid() }}"><label class="text-sm font-semibold">Renewal date<input type="date" name="renewal_date" required class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><label class="text-sm font-semibold">Offering<select name="offering_key" class="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3"><option value="">Repeat current offering / custom terms</option>@foreach(\App\Domains\Students\Services\StudentLedgerService::PRESETS as $key => $preset)<option value="{{ $key }}">{{ $preset['name'] }} · {{ $preset['price'] }} USD</option>@endforeach</select></label><label class="text-sm font-semibold">Custom purchase expiry (optional)<input type="date" name="expiration_date" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></label><x-operational-reason-select /><label class="text-sm font-semibold sm:col-span-2">Notes (optional)<textarea name="notes" maxlength="1000" rows="2" class="mt-1 block w-full rounded-xl border border-slate-300 p-3"></textarea></label><button class="min-h-11 justify-self-start rounded-xl bg-amber-700 px-5 py-3 text-sm font-semibold text-white">Create renewal purchase</button></form></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="mb-4 text-xl font-bold">Renewal history from this purchase</h2>@forelse($renewals as $renewal)<p class="border-t border-slate-100 py-3 text-sm">{{ $renewal->renewal_date->toDateString() }} · <a class="font-semibold text-amber-800" href="{{ route('admin.packages.lifecycle', $renewal->new_package_id) }}">New purchase #{{ $renewal->new_package_id }} · {{ $renewal->newPackage->package_name }}</a> · {{ str_replace('_', ' ', $renewal->reason_code ?? 'No reason recorded') }}@if($renewal->notes)<span class="mt-2 block whitespace-pre-wrap text-slate-600">{{ $renewal->notes }}</span>@endif</p>@empty<p class="text-sm text-slate-500">No renewals recorded.</p>@endforelse{{ $renewals->links() }}</section></div>
@endsection
