@extends($studentView ? 'layouts.student' : 'layouts.admin')
@section('content')
<style>@media print { #admin-sidebar, header, [data-statement-tools], .whatsapp-cta { display:none !important; } #admin-content { margin-left:0 !important; } body, main { background:white !important; } }</style>
<div class="mx-auto max-w-5xl space-y-6"><div><p class="text-xs font-bold uppercase tracking-widest text-slate-500">{{ $receipt ? 'Payment receipt' : 'Package financial statement' }}</p><h1 class="mt-2 font-serif text-3xl font-bold">{{ $package->package_name }} · Purchase #{{ $package->id }}</h1><p class="mt-2 text-sm text-slate-600">{{ $package->student?->name ?? 'Historical student' }} · {{ $package->currency }} · Dates shown in {{ $timezone }}</p></div>
<div data-statement-tools x-data class="flex flex-wrap gap-3"><button @click="window.print()" class="min-h-11 rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Print / save PDF</button>@foreach(['csv', 'xlsx'] as $format)<a class="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold" href="{{ route($studentView ? 'student.statements.export' : 'admin.statements.export', ['package' => $package, 'format' => $format]) }}">Statement {{ strtoupper($format) }}</a>@endforeach<a class="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold" href="{{ $studentView ? route('student.statements.index') : route('admin.packages.lifecycle', $package) }}">{{ $studentView ? 'All statements' : 'Installments & renewal' }}</a></div>
@if(! $receipt)<section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['final_price' => 'Purchase price', 'net_paid' => 'Net actual payments', 'balance_due' => 'Outstanding now', 'overpaid' => 'Overpayment now'] as $key => $label)<div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-bold">{{ $key === 'final_price' ? $package->final_price : $summary[$key] }} {{ $package->currency }}</p></div>@endforeach</section><p class="text-sm text-slate-600">Typed credit balance: {{ $summary['balance_text'] }} · {{ $summary['entitlement_status'] }}</p>@endif
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">{{ $receipt ? 'Actual payment #'.$receipt->id : 'Actual payment history' }}</h2><p class="mt-2 text-sm text-slate-600">Payments are recorded through the manual cashier workflow. Internal record numbers identify this application’s entries. An external reference appears only when it was recorded; it does not certify provider settlement.</p>
<div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-3">Record / date</th><th class="p-3">Amount</th><th class="p-3">Recorded method</th><th class="p-3">Recorded external reference</th></tr></thead><tbody>@forelse($receipt ? collect([$receipt]) : $package->payments as $payment)<tr class="border-t border-slate-100"><td class="p-3"><a href="{{ route($studentView ? 'student.receipts.show' : 'admin.receipts.show', ['package' => $package, 'payment' => $payment->id]) }}" class="font-semibold text-amber-800">Payment #{{ $payment->id }}</a><p class="mt-1 text-xs text-slate-500">{{ $payment->paid_at->setTimezone($timezone)->format('Y-m-d H:i') }}</p></td><td class="p-3 font-semibold">{{ $payment->amount_paid }} {{ $package->currency }}</td><td class="p-3">{{ $payment->payment_method ?: 'Manual payment' }}</td><td class="p-3 break-all">{{ $payment->transaction_reference ?: 'Not recorded' }}</td></tr>@empty<tr><td colspan="4" class="p-4 text-slate-500">No actual payments recorded.</td></tr>@endforelse</tbody></table></div>
<h3 class="mb-3 mt-6 font-semibold">Actual refunds{{ $receipt ? ' against this payment' : '' }}</h3>@forelse($receipt ? $package->refunds->where('payment_record_id', $receipt->id) : $package->refunds as $refund)<p class="border-t border-slate-100 py-3 text-sm">Refund #{{ $refund->id }} · Original payment #{{ $refund->payment_record_id }} · {{ $refund->amount_refunded }} {{ $package->currency }} · {{ $refund->refunded_at->setTimezone($timezone)->format('Y-m-d H:i') }}</p>@empty<p class="text-sm text-slate-500">No actual refunds recorded.</p>@endforelse</section>
@if(! $receipt && count($installments))<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="mb-4 text-xl font-bold">Expected installments — forecast only</h2><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-3">Due date</th><th class="p-3">Expected</th><th class="p-3">Outstanding forecast</th><th class="p-3">Computed status</th></tr></thead><tbody>@foreach($installments as $row)<tr class="border-t border-slate-100"><td class="p-3">{{ $row['due_date'] }}</td><td class="p-3">{{ $row['expected_amount'] }}</td><td class="p-3">{{ $row['due'] }}</td><td class="p-3">{{ str_replace('_', ' ', $row['status']) }}</td></tr>@endforeach</tbody></table></div></section>@endif
<p class="text-xs text-slate-500">Generated {{ now($timezone)->format('Y-m-d H:i') }} {{ $timezone }}. Statements reflect current append-only payment and refund records.</p></div>
@endsection
