@extends('layouts.admin')
@section('content')
<div class="space-y-6">
    <header><h1 class="font-serif text-3xl font-bold">Learning analytics</h1><p class="mt-2 text-slate-600">Current learning outcomes and trusted video coverage.</p></header>
    @include('admin.lms.operations._nav')
    @include('admin.lms.operations._filters',['dates'=>true])
    <p class="rounded-xl bg-amber-50 p-4 text-xs leading-6 text-amber-950">{{ $cohort }} Completion measures enrolled learners and current requirements. Open-access learning without a retained enrollment is outside this cohort.</p>
    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(['active_learners'=>'Learners with latest visit in period','active_enrollments'=>'Currently accessible enrollments','enrolled'=>'Retained enrollments','started'=>'Started current curriculum','completed'=>'Completed current curriculum','completion_rate'=>'Completion rate (%)','lessons_completed'=>'Lessons completed','quiz_attempts'=>'Quiz submissions in period','quiz_passes'=>'Passed submitted attempts','assignments_submitted'=>'Assignment submissions','assignments_reviewed'=>'Submissions reviewed','assignments_awaiting_review'=>'Awaiting final review'] as $key=>$label)<article class="rounded-2xl border border-slate-200 bg-white p-4"><h2 class="text-xs font-semibold text-slate-600">{{ $label }}</h2><p class="mt-3 text-2xl font-bold tabular-nums">{{ $summary[$key] }}</p></article>@endforeach</div>
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="text-xl font-semibold">Course outcomes</h2><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">Current enrolled course outcomes</caption><thead class="border-b text-xs text-slate-500"><tr><th scope="col" class="p-3">Course</th><th scope="col" class="p-3">Enrolled</th><th scope="col" class="p-3">Started</th><th scope="col" class="p-3">Completed</th><th scope="col" class="p-3">Completion rate</th><th scope="col" class="p-3">Average progress</th><th scope="col" class="p-3">Graded quiz average</th><th scope="col" class="p-3">Reviews</th></tr></thead><tbody>@forelse($courseRows as $row)<tr class="border-b border-slate-100"><th scope="row" dir="auto" class="p-3 font-semibold">{{ $row['course']->title }}</th><td class="p-3 tabular-nums">{{ $row['enrolled'] }}</td><td class="p-3 tabular-nums">{{ $row['started'] }}</td><td class="p-3 tabular-nums">{{ $row['completed'] }}</td><td class="p-3 tabular-nums">{{ $row['completion_rate'] }}%</td><td class="p-3 tabular-nums">{{ $row['average_progress'] }}%</td><td class="p-3 tabular-nums">{{ $row['quiz_average']??'—' }}</td><td class="p-3"><a href="{{ route('admin.lms.reviews.index',$row['course']) }}" class="inline-flex min-h-11 items-center font-semibold text-amber-800">Open reviews</a></td></tr>@empty<tr><td colspan="8" class="p-6 text-slate-500">No enrolled learning in this selection.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $courseRows->links() }}</div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="text-xl font-semibold">Protected video placements</h2><p class="mt-2 text-xs leading-6 text-slate-500">Unique verified coverage from learning progress, per Student and lesson video placement. Coverage measures watched ranges; it does not measure attention or total study time. No detailed heatmap is inferred.</p><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">Current verified video coverage for placements started in the period</caption><thead class="border-b text-xs text-slate-500"><tr><th scope="col" class="p-3">Video</th><th scope="col" class="p-3">Started</th><th scope="col" class="p-3">25%</th><th scope="col" class="p-3">50%</th><th scope="col" class="p-3">75%</th><th scope="col" class="p-3">Threshold met</th><th scope="col" class="p-3">Average coverage</th><th scope="col" class="p-3">Average covered seconds</th></tr></thead><tbody>@forelse($videoRows as $row)<tr class="border-b border-slate-100"><th scope="row" dir="auto" class="p-3 font-semibold">{{ $row['label'] }}<span class="mt-1 block text-xs font-normal text-slate-500">{{ $row['course']->title }} · Lesson #{{ $row['lesson_id'] }}</span></th>@foreach(['started','25','50','75','completed'] as $key)<td class="p-3 tabular-nums">{{ $row[$key] }}</td>@endforeach<td class="p-3 tabular-nums">{{ $row['average_percent'] }}%</td><td class="p-3 tabular-nums">{{ $row['average_seconds'] }}</td></tr>@empty<tr><td colspan="8" class="p-6 text-slate-500">No current protected video coverage in this selection.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $videoRows->links() }}</div></section>
</div>
@endsection