@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-5xl space-y-6"><header><h1 class="font-serif text-3xl font-bold">LMS settings</h1><p class="mt-2 text-slate-600">Global defaults and current operational thresholds.</p></header>@include('admin.lms.operations._nav')
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="text-xl font-semibold">Video security & Bunny</h2><p class="mt-2 text-sm text-slate-600">Bunny {{ $provider?->enabled?'enabled':'not enabled' }}. Credentials, protection profiles and device/stream limits use their existing protected settings.</p><a href="{{ route('admin.lms.video.settings') }}" class="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-amber-800">Open protected video settings</a></section>
    <form method="POST" action="{{ route('admin.lms.settings.update') }}" class="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6">@csrf<input type="hidden" name="version" value="{{ $document['version'] }}">
        <section class="space-y-4"><h2 class="text-xl font-semibold">Learning defaults</h2><x-lms.input name="video_threshold" id="default-video-threshold" label="Default watched threshold for new learning (%)" type="number" min="1" max="100" :required="true" :value="old('video_threshold',$document['values']['video_threshold'])"/><p class="text-xs text-slate-500">New content captures this default. Existing authored rules keep their explicit values.</p><label for="catalog-profile" class="block text-sm font-semibold">Global catalog fallback profile<select id="catalog-profile" name="default_catalog_profile_id" class="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">Existing Member default</option>@foreach($profiles as $profile)<option value="{{ $profile->id }}" @selected((int)old('default_catalog_profile_id',$document['values']['default_catalog_profile_id'])===$profile->id)>{{ $profile->name }}</option>@endforeach</select></label><p class="text-xs leading-6 text-slate-500">Explicit lesson profile → explicit course profile → catalog fallback. Private learning keeps its strong Private fallback. Limits remain in each profile.</p></section>
        <section class="space-y-4"><h2 class="text-xl font-semibold">Attention thresholds</h2><div class="grid gap-4 sm:grid-cols-2">@foreach(['inactivity_days'=>['Inactive days',365],'stalled_days'=>['Days without new lesson completion',365],'quiz_failures'=>['Quiz failures without a current pass',20],'expiry_days'=>['Access ending within days',30],'low_progress_percent'=>['Low progress below (%)',99],'private_unopened_days'=>['Private follow-up unopened for days',365]] as $key=>[$label,$max])<x-lms.input :name="$key" :id="'attention-'.$key" :label="$label" type="number" min="1" :max="$max" :required="true" :value="old($key,$document['values'][$key])"/>@endforeach</div></section>
        <section class="space-y-3"><h2 class="text-xl font-semibold">Visit-synchronized notifications</h2>@foreach(['expiry_notifications'=>'Access nearing expiry','drip_notifications'=>'Scheduled lessons unlocked'] as $key=>$label)<input type="hidden" name="{{ $key }}" value="0"><label class="flex min-h-11 items-center gap-3 text-sm"><input name="{{ $key }}" type="checkbox" value="1" @checked(old($key,$document['values'][$key]))>{{ $label }}</label>@endforeach<p class="text-xs leading-6 text-slate-500">Eligible facts appear when the Student visits their area. Assignment/review notifications and read state keep their existing behavior.</p></section><x-lms.button>Save LMS settings</x-lms.button>
    </form>
</div>
@endsection